version: 2

project_name: chikuchiku

before:
  hooks:
    - go mod tidy

builds:
  - id: chikuchiku
    main: ./cmd/chikuchiku/
    binary: chikuchiku
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}

changelog:
  use: github
